### ISSUE TITLE
Screenshot Not working on Failure

### ISSUE THREAD

**Issue by nimathing2052** [Tahanima/playwright-test-automation-boilerplate#5]
Hello Tahanima,

Whenever test cases fails I am neither seeing the test failed screenshots, nor it gets appeared in the Test Report.

Could you please check?

Regards,
Nima Thing

**Comment by Tahanima** [comment]
> Hello Tahanima,
> 
> Whenever test cases fails I am neither seeing the test failed screenshots, nor it gets appeared in the Test Report.
> 
> Could you please check?
> 
> Regards, Nima Thing

Hi @nimathing2052 
Thanks for reporting the issue. It should be fixed now.

**Comment by nimathing2052** [comment]
Thanks, it is working as expected. Cheers!
